site_name: My Docs
site_author: AllenGao
repo_name: 'AllenGao731/MkDocs'
repo_url: https://github.com/AllenGao731/MkDocs

nav:
  - 主页:
    - Welcome to MkDocs: index.md
  - 语言基础:
    - C++代码框架: lang/cpp.md
    - 输入输出: lang/io.md
    - 变量: lang/variable.md

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy
    - navigation.top
    - search.suggest
    - search.highlight